name: Build OWRT

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build OWRT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix libfuse-dev
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

          sudo mkdir -p /mnt/build_owrt
          sudo chown $USER:$USER /mnt/build_owrt
          sudo ln -s /mnt/build_owrt $GITHUB_WORKSPACE/owrt

      - name: Clone Code
        run: |
          git clone --depth=1 --single-branch --branch main https://github.com/VIKINGYFY/immortalwrt.git ./owrt/
          cd ./owrt/ && echo "OWRT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV

      - name: Check Caches
        id: check-cache
        uses: actions/cache@v5
        with:
          key: owrt-${{ env.OWRT_HASH }}
          restore-keys: owrt
          path: |
            ./owrt/.ccache
            ./owrt/staging_dir/host*
            ./owrt/staging_dir/tool*

      - name: Update Caches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -d "./owrt/staging_dir" ]; then
            find "./owrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
              find "$DIR" -type f -exec touch {} +
            done

            mkdir -p ./owrt/tmp && echo "1" > ./owrt/tmp/.build

            echo "toolchain skipped done!"
          else
            echo "caches missed!"
          fi

          if [ "${{ steps.check-cache.outputs.cache-hit }}" != "true" ]; then
            CACHE_LIST=$(gh cache list --key "owrt" | cut -f 1)
            for CACHE_KEY in $CACHE_LIST; do
              gh cache delete "$CACHE_KEY"
            done

            echo "caches cleanup done!"
          fi

      - name: Update Feeds
        run: |
          cd ./owrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Replace Argon-theme
        run: |
          cd ./owrt/
          rm -rf feeds/luci/themes/luci-theme-argon
          rm -rf feeds/luci/applications/luci-app-argon-config
          mkdir -p package/argon
          cd package/argon
          git clone https://github.com/jerrykuku/luci-theme-argon.git --depth=1 --single-branch --branch master
          git clone https://github.com/jerrykuku/luci-app-argon-config.git --depth=1 --single-branch --branch master

      - name: Compile Firmware
        run: |
          cd ./owrt/
          cat $GITHUB_WORKSPACE/Redmi-AX5.config >> .config
          make defconfig -j$(nproc)
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Package Firmware
        run: |
          cd ./owrt/ && mkdir -p ./upload/
          cp -f ./.config ./upload/config-"$OWRT_HASH".txt
          echo "OWRT_KVER=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)" >> $GITHUB_ENV
          echo "OWRT_LIST=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^luci-(app|theme)[^ ]*' {} \; | tr '\n' ' ')" >> $GITHUB_ENV
          find ./bin/targets/ -iregex ".*\(buildinfo\|json\|packages\)$" -exec rm -rf {} +
          find ./bin/targets/ -type f -exec mv -f {} ./upload/ \;
          make clean -j$(nproc)

      - name: Release Firmware
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{env.OWRT_HASH}}
          files: ./owrt/upload/*
          body: |
            提交：${{env.OWRT_HASH}}
            内核版本：${{env.OWRT_KVER}}
            插件列表：${{env.OWRT_LIST}}

      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 3
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 30
